### ISSUE TITLE
Support for unity 6 lts

### ISSUE THREAD

**Issue by sureneazx** [learntoflutter/flutter_embed_unity#40]
When we can expect a release for unity 6.
Also any plans to support windows build?

**Comment by jamesncl** [comment]
There currently isn't a timeline for supporting Unity 6, but it's something I'd like to add. Just to be clear to set your expectations: this isn't a commercial endeavor, it's just myself and some great collaborators who have decided to work together in our spare time to make this available publicly for free, so it entirely depends on our other commitments and how much others like yourself are willing to contribute (also I have an autoimmune disease which causes chronic pain and fatigue, so I'm not able to work full time).

I do know that @timbotimbo started experimenting with Unity 6 support in [a branch of his fork](https://github.com/timbotimbo/flutter_embed_unity/commits/Unity_6000_android), if you're interested in contributing you might want to check that out. There is some additional [documentation in the wiki for contributors](https://github.com/learntoflutter/flutter_embed_unity/wiki). This flutter_embed_unit is a [federated plugin](https://docs.flutter.dev/packages-and-plugins/developing-packages), which means that we can support Unity 6 using a separate package for each platform, without impacting existing Unity 2022.3 support.

I myself will need Unity 6 and web support for an upcoming project, so I am planning to start working on Unity 6 in the next couple of months or so, I will likely build upon the fork mentioned above, and also add web as an additional platform. I don't believe anyone has discussed windows support before so this may be something you will have to contribute yourself.

Hope that clarifies the situation!

**Comment by jamesncl** [comment]
I've re-opened this issue as it's probably a good place to discuss Unity 6 support

**Comment by jamesncl** [comment]
@sureneazx there is [a branch in active development to support Unity 6](https://github.com/learntoflutter/flutter_embed_unity/tree/feat/unity6). It isn't published to pub.dev yet, but you can try it out by adding the following dependency in your pubspec.yaml:

```yaml
  flutter_embed_unity: ^1.2.7  # Or whatever the latest version is
  # Add this:
  flutter_embed_unity_6000_0_android:
    git:
      url: https://github.com/learntoflutter/flutter_embed_unity.git
      ref: feat/unity6
      path: flutter_embed_unity_6000_0_android/
```

Then export your Unity project in the same way as before using Unity 6000.0. You will also need to remove the `ndkPath` property from your unityLibrary/build.gradle (a new export script will be available soon which does this automatically). This should then work, for both android and ios (ios does not need any additional dependency)

Be warned though - consider this an early alpha release, unstable and not thoroughly tested. If you find any issues please raise one!

**Comment by jamesncl** [comment]
This is now [published as a pre-release](https://pub.dev/packages/flutter_embed_unity/versions/1.3.0-beta.1) so you can use:

```yaml
dependencies:
  flutter_embed_unity: ^1.3.0-beta.1
  flutter_embed_unity_6000_0_android: ^1.2.1-beta.1
```
