### ISSUE TITLE
onMessageFromUnity not working in Android - 1.3.0-beta.1

### ISSUE THREAD

**Issue by Oppenheimr** [learntoflutter/flutter_embed_unity#47]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Unity version

Unity 6000.0 LTS

### Common issues

- [x] I have checked the common issues

### Flutter version

3.32.1

### Description

Hi guys, we are using this plugin with following dependencies;

```
  flutter_embed_unity: ^1.3.0-beta.1
  flutter_embed_unity_6000_0_android: ^1.2.1-beta.1
```

Our flutter code;

```
EmbedUnity(
              onMessageFromUnity: (String message) {
                print(message);
                try {
                  final decoded = json.decode(message);
                  if (decoded is Map<String, dynamic> &&
                      decoded.containsKey('game') &&
                      decoded.containsKey('reward') &&
                      decoded.containsKey('score')) {
                    final String game = decoded['game'];
                    final int reward = decoded['reward'];
                    final int score = decoded['score'];

                    addRewardToUser(game, reward);
                    sendScore(game, score);
                  }
                } catch (e) {
                  print("Invalid JSON or unexpected format: $e");
                }
              },
            ),
```

Our C# code;

```
    public static class UnityFlutterCommunication
    {
        /// <summary>
        /// Sends game statistics to Flutter, waits briefly, then quits the application.
        /// </summary>
        /// <param name="data">GameStatistic object to be sent</param>
        public static async void BackToFlutter(GameStatistic data)
        {
            if (data == null)
            {
                Debug.LogWarning("GameStatistic data is null. Cannot send to Flutter.");
                return;
            }

            try
            {
                var json = data.ToJson();
                Debug.Log($"BackToFlutter, sending data: {json}");
                SendToFlutter.Send(json);
                await Task.Delay(300); // Ensure message is sent before quitting
                //Application.Quit();
            }
            catch (Exception e)
            {
                Debug.LogError($"[BackToFlutter] Exception occurred: {e}");
                // You can trigger a fallback or log this externally
            }
        }
    }

    [Serializable]
    public class GameStatistic
    {
        public string game;
        public int reward;
        public int score;

        public GameStatistic(string game, int reward, int score)
        {
            this.game = game;
            this.reward = reward;
            this.score = score;
        }

        /// <summary>
        /// Converts the GameStatistic object to JSON string.
        /// </summary>
        public string ToJson()
        {
            return JsonUtility.ToJson(this);
        }
    }
```

im calling;

```
            try
            {
                var json = data.ToJson();
                Debug.Log($"BackToFlutter, sending data: {json}");
                SendToFlutter.Send(json);
                await Task.Delay(300); // Ensure message is sent before quitting
                //Application.Quit();
            }
            catch (Exception e)
            {
                Debug.LogError($"[BackToFlutter] Exception occurred: {e}");
                // You can trigger a fallback or log this externally
            }
```

This implementation is working perfectly on ios we tested it with @aykutuludag but it **is not working  on android**.

### What platforms are you seeing the problem on?

Android

### Devices

Xiaomi Redmi note 13 - not worked. onMessageFromUnity not called
Iphone 14 - works perfectly

**Comment by timbotimbo** [comment]
Are you using other Flutter plugins that do background processing (push notifications, alarms, etc.) ?
Please share the plugins in your pubspec.yaml.

You might be running into this https://github.com/learntoflutter/flutter_embed_unity/pull/46.

Application.quit will kill your entire Flutter app, not just Unity.

**Comment by aykutuludag** [comment]
> Are you using other Flutter plugins that do background processing (push notifications, alarms, etc.) ? Please share the plugins in your pubspec.yaml.
> 
> You might be running into this [#46](https://github.com/learntoflutter/flutter_embed_unity/pull/46).
> 
> Application.quit will kill your entire Flutter app, not just Unity.

Okay then we are not gonna using Application.quit. We tried on apple side it is actually kill the whole app then we rollback it.

Here is our dependencies:

```
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icon.
  cupertino_icons: ^1.0.8
  # google
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_analytics: ^11.5.0
  firebase_analytics_web: ^0.5.10+13
  firebase_messaging: ^15.2.7
  firebase_crashlytics: ^4.3.7
  google_mobile_ads: ^6.0.0
  shared_preferences: ^2.4.0
  wakelock_plus: ^1.2.10
  device_info_plus: ^11.5.0
  app_tracking_transparency: ^2.0.6+1
  provider: ^6.1.2
  auto_route: ^10.1.0+1
  intl: ^0.20.2
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  rate_my_app: ^2.3.1
  flutter_svg: ^2.2.0
  flutter_story_view:
    git:
      url: https://github.com/aykutuludag/flutter_story_view.git
      ref: master
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.4
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  flutter_native_splash: ^2.4.6
  flutter_inappwebview: ^6.1.5
  permission_handler: ^12.0.0+1
  alarm: ^5.1.4
  flutter_embed_unity: ^1.3.0-beta.1
  flutter_embed_unity_6000_0_android: ^1.2.1-beta.1
  collection: ^1.19.1
  fluttertoast: ^8.2.10
  in_app_purchase: ^3.2.3
```

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.1
  auto_route_generator: ^10.1.0+1
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.4
```
